name: IntelliCode

on:
  push:
    branches:
      - master
      
jobs:
  build:
    runs-on: windows-latest

    steps:
    
    - name: Check out code
      uses: actions/checkout@v1
    
    - name: Dotnet Build
      run: |
           cd "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\"
           .\MSBuild.exe $Env:GITHUB_WORKSPACE\TrueCraft.sln
    - name: Train Intellicode Model
      uses: osobeso/intellicode-team-model/releases@v1
      with: 
        pat-token: ${{ secrets.VSIC_PAT_TOKEN }}
        directory: ${{ github.workspace }}
      
